# image from:
# https://github.com/dagster-io/dagster/blob/1.8.4/examples/deploy_docker/docker-compose.yml

version: "3.7"

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    networks:
      - docker_network

  user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: user_code
    image: user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "user"
      DAGSTER_POSTGRES_PASSWORD: "password"
      DAGSTER_POSTGRES_DB: "postgres"
      DAGSTER_POSTGRES_PORT: 5432
      DAGSTER_CURRENT_IMAGE: "user_code_image"
    networks:
      - docker_network

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "user"
      DAGSTER_POSTGRES_PASSWORD: "password"
      DAGSTER_POSTGRES_DB: "postgres"
      DAGSTER_POSTGRES_PORT: 5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_network
    depends_on:
      - db
      - user_code

  daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "user"
      DAGSTER_POSTGRES_PASSWORD: "password"
      DAGSTER_POSTGRES_DB: "postgres"
      DAGSTER_POSTGRES_PORT: 5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_network
    depends_on:
      - db
      - user_code

networks:
  docker_network:
    driver: bridge
    name: docker_network
